### PR TITLE
🐛 Fixed BookmarkNode not auto selecting in Editor

### PR DESCRIPTION
**Pull request by ronaldlangeveld**
ref https://ghost.slack.com/archives/C02G9E68C/p1713864338521819

- Fixes an issue where the BookmarkNode didn't initialise selected upon creating a new Bookmark card.
- This fix makes use of the "INSERT_CARD_COMMAND" that takes the selections into account at plugin level and removes the `$insertAndSelectNode` initialising function.

### CODE REVIEW

**Review by kevinansfield — CHANGES_REQUESTED** [review]
I don't think this is the right fix. We should never be doing anything with selection during component rendering because that pulls control away from Lexical and will end up with odd things happening like selection being changed purely because a post was opened or content pasted when containing a bookmark card.

**Comment by ronaldlangeveld** [comment]
> I don't think this is the right fix. We should never be doing anything with selection during component rendering because that pulls control away from Lexical and will end up with odd things happening like selection being changed purely because a post was opened or content pasted when containing a bookmark card.

Thanks for the feedback. 

There's another node, `GalleryNodeComponent` that takes a similar approach. Will keep investigating.

**Comment by kevinansfield** [comment]
The gallery card only reads the selected node key, it doesn't set it. I think it's that way because it was created around the time we were still working out how selection would be passed through the context/component tree.

**Comment by ronaldlangeveld** [comment]
> The gallery card only reads the selected node key, it doesn't set it. I think it's that way because it was created around the time we were still working out how selection would be passed through the context/component tree.

Found the real fix. Thanks for the heads up! Should be good now. :)

**Pull request merged**
